files:
  - source: /resources/lang/source/*.*
    translation: /resources/lang/%two_letters_code%/%original_file_name%
  - source: /resources/lang/source/email/*.*
    translation: /resources/lang/%two_letters_code%/email/%original_file_name%
  - source: /resources/lang/source/html/*.*
    translation: /resources/lang/%two_letters_code%/html/%original_file_name%
